# Generated by Django 4.0.1 on 2022-01-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
