# Generated by Django 4.0.1 on 2022-01-17 04:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_video_slug_alter_video_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='video_name', unique=True),
        ),
    ]
