# Generated by Django 4.0.1 on 2022-01-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='desc',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
