# Generated by Django 4.0.1 on 2022-01-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_video_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
