# Generated by Django 4.0.1 on 2022-01-17 07:30

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_alter_video_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='video',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='playlist',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='playlist_name', unique=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(to='Courses.Video'),
        ),
    ]
